### ISSUE TITLE
Gracefully handle missing event subscription info in the omg config

### ISSUE THREAD

**Issue by judepereira** [asyncy/platform-engine#157]
If the event subscription HTTP config is missing from the OMG config, then the engine attempts to make a HTTP call with `http://service:80/None`:
```
DEBUG:asyncy:Sending subscription request to http://asyncy--03f5ece8-e6e6-42e1-bd2b-74a6b57a2739-redis-1.03f5ece8-e6e6-42e1-bd2b-74a6b57a2739.svc.cluster.local:80None

DEBUG:asyncy:Subscribing to rds from listener...
ERROR:asyncy:Failed to bootstrap story
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/App.py", line 59, in run_stories
    await Story.run(self, self.logger, story_name)
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/processing/Story.py", line 148, in run
    raise err
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/processing/Story.py", line 138, in run
    await cls.execute(logger, story)
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/processing/Story.py", line 35, in execute
    line_number = await Story.execute_line(logger, story, line_number)
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/processing/Story.py", line 72, in execute_line
    raise e
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/processing/Story.py", line 65, in execute_line
    return await Lexicon.when(logger, story, line)
  File "/usr/local/lib/python3.6/site-packages/asyncy_platform_engine-0.0.2-py3.6.egg/asyncy/processing/Lexicon.py", line 213, in when
    story=story, line=line)
```

This can be handled gracefully.

**Comment by judepereira** [comment]
Not required as the microservice.yaml file will be validated before a service can be submitted.
